name: nsmp_dashboards
description: An absolute bare-bones web app.
version: 1.0.0
homepage: https://www.example.com
author: mdemyanov <mdemyanov@naumen.ru>

environment:
  sdk: '>=2.0.0 < 3.0.0'

dependencies:
  http: "^0.11.3+17"
  dart_apex_charts: "^0.2.4"
  naumen_smp_jsapi: "^1.0.2"

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0

